version: "3"

services:
  web:
    build: .
    container_name: 4rc-vtb
    command: >
      sh -c "python manage.py makemigrations --noinput &&
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./:/4RC
    env_file:
      - .env.dev
