# Generated by Django 4.1.2 on 2022-10-07 17:07

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title', unique=True, verbose_name='url')),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
    ]
