# Generated by Django 4.1.2 on 2022-10-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_account_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
            ],
        ),
    ]
