# Generated by Django 4.1.2 on 2022-10-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_monthlypay'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypay',
            name='group',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
