# Generated by Django 4.1.2 on 2022-10-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_monthlypay_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
