# Generated by Django 4.1.2 on 2022-10-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_account_group_alter_account_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.CharField(choices=[('employee', 'employee'), ('editor', 'editor'), ('admin', 'admin')], max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='icon',
            field=models.ImageField(blank=True, default='icon.png', upload_to=''),
        ),
    ]
