# Generated by Django 4.1.2 on 2022-10-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_account_group_alter_account_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.CharField(choices=[('employee', 'employee'), ('admin', 'admin'), ('editor', 'editor')], max_length=100),
        ),
    ]
