# Generated by Django 4.1.2 on 2022-10-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_account_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.CharField(choices=[('employee', 'employee'), ('editor', 'editor'), ('admin', 'admin')], max_length=100),
        ),
    ]
