# Generated by Django 4.1.2 on 2022-10-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
